clc;
x1=input('enter the first sequence'); 
subplot(3,1,1);
stem(x1);
ylabel('amplitude');
title('plot of the first sequence'); 
x2=input('enter 2nd sequence');
subplot(3,1,2);
stem(x2);
ylabel('amplitude'); 
title('plot of 2nd sequence'); 
f=conv(x1,x2);
disp('output of linear conv is'); 
disp(f);
xlabel('time index n'); 
ylabel('amplitude f'); 
subplot(3,1,3); 
stem(f);
title('linear conv of sequence');
